name: "Silly programmer"
subname: "side effects guaranteed"
paginate: 25
url: https://hradecek.github.io/
blog_theme: dark # light | dark

about_enabled: true
discus_identifier: hradecek
ga_analytics: # GA Tracking Id
local_fonts: true
rss_enabled: true
scrollappear_enabled: true
social:
  email:         ivohradek@gmail.com
  github:        hradecek
  linkedin:      ivo-hrádek-01baa8115
  #  facebook:   Don't use such a thing!
  stackoverflow: 772992/ivo-hrádek

# Important settings (change at own risk)
assets:
  features:
    automatic_img_size: false
  sources:
    - _assets
    - _assets/fonts
    - _assets/images
collections:
  tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: articles_by_tag
markdown: kramdown
kramdown:
highlighter: rouge
exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - webpack.config.js
  - node_modules/
  - src/
  - bin/
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
